workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Fix Capacitor permissions + Sync
        script: |
          chmod +x node_modules/.bin/cap
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     archive \
                     -archivePath build/App.xcarchive

    artifacts:
      - ios/App/build/**/*.ipa